// importing the SideBar component
import Sidebar from "@/components/Sidebar";
import "./globals.css";
// importing the Figtree font from google
import { Figtree } from 'next/font/google'

// setting the font styling to be latin
const font = Figtree({ subsets: ['latin'] })

// Just general metadata for the app
export const metadata = {
  title: 'Spotify Clone',
  description: 'Generated by create next app - Modified by Gio for Music Listeners;)'
}

// This was all done to change the font btw lol
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Sidebar>
          {children}
        </Sidebar>
      </body>
    </html>
  )
}